/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.siserpjava.views;

/**
 *
 * @author yukit
 */

//import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;
public class frmLoginOrange extends javax.swing.JFrame {
    public boolean blnAnimacion = false;
    public int MovtoX,MovtoY;

    /**
     * Creates new form frmLoginOrange
     */
    public frmLoginOrange() {    
        initComponents();
        this.setLocationRelativeTo(null); 
    }
    public void openInternet(){
        try{
            Desktop.getDesktop().browse(URI.create("www.siesa.com"));
        } catch(Exception e){
            JOptionPane.showConfirmDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblRegistro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblMusica = new javax.swing.JLabel();
        lblCalculadora = new javax.swing.JLabel();
        lblInternet = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblMovil = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        jpApplicactions = new javax.swing.JScrollPane();
        jpMenu = new javax.swing.JPanel();
        lblApp1 = new javax.swing.JLabel();
        lblApp6 = new javax.swing.JLabel();
        lblApp5 = new javax.swing.JLabel();
        lblApp4 = new javax.swing.JLabel();
        lblApp2 = new javax.swing.JLabel();
        lblApp3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lblApp7 = new javax.swing.JLabel();
        lblApp8 = new javax.swing.JLabel();
        lblApp9 = new javax.swing.JLabel();
        lblApp10 = new javax.swing.JLabel();
        lblApp11 = new javax.swing.JLabel();
        lblApp12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jpIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 90, 35)));
        jpIngreso.setForeground(new java.awt.Color(204, 204, 204));
        jpIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setText("User:");
        jpIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 179, 258, -1));

        lblRegistro.setBackground(new java.awt.Color(238, 112, 82));
        lblRegistro.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblRegistro.setForeground(new java.awt.Color(238, 112, 82));
        lblRegistro.setText("Aquí...");
        lblRegistro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblRegistroMouseMoved(evt);
            }
        });
        lblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistroMouseClicked(evt);
            }
        });
        jpIngreso.add(lblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 40, -1));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_User_96px_2.png"))); // NOI18N
        jpIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 76, -1, -1));

        jLabel4.setBackground(new java.awt.Color(238, 112, 82));
        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 112, 82));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Key_32px.png"))); // NOI18N
        jpIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 297, -1, -1));

        lblMenu.setBackground(new java.awt.Color(238, 112, 82));
        lblMenu.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(238, 112, 82));
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Menu_32px.png"))); // NOI18N
        lblMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });
        jpIngreso.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Ingrese Usuario");
        jTextField1.setBorder(null);
        jpIngreso.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 219, 29));
        jpIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 248, 219, 12));
        jpIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 341, 222, 10));

        jPasswordField1.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jpIngreso.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 297, 222, 38));

        jLabel6.setBackground(new java.awt.Color(238, 112, 82));
        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 112, 82));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_customer_32px_1.png"))); // NOI18N
        jpIngreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 210, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/Enter_OFF.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/Enter_ON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/Enter_ON.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/Enter_ON.png"))); // NOI18N
        jpIngreso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 362, -1, -1));

        lblMusica.setBackground(new java.awt.Color(238, 112, 82));
        lblMusica.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblMusica.setForeground(new java.awt.Color(238, 112, 82));
        lblMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Musical_Notes_32px.png"))); // NOI18N
        jpIngreso.add(lblMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -30, -1, -1));

        lblCalculadora.setBackground(new java.awt.Color(238, 112, 82));
        lblCalculadora.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblCalculadora.setForeground(new java.awt.Color(238, 112, 82));
        lblCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Calculator_32px.png"))); // NOI18N
        lblCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCalculadoraMouseClicked(evt);
            }
        });
        jpIngreso.add(lblCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -30, -1, -1));

        lblInternet.setBackground(new java.awt.Color(238, 112, 82));
        lblInternet.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblInternet.setForeground(new java.awt.Color(238, 112, 82));
        lblInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Globe_32px.png"))); // NOI18N
        lblInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInternetMouseClicked(evt);
            }
        });
        jpIngreso.add(lblInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, -30, -1, -1));

        jLabel5.setBackground(new java.awt.Color(238, 112, 82));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 112, 82));
        jLabel5.setText("Password:");
        jpIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 266, 258, -1));

        jLabel7.setBackground(new java.awt.Color(238, 112, 82));
        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 112, 82));
        jLabel7.setText("Si no esta registrado haga click ");
        jpIngreso.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 160, -1));

        getContentPane().add(jpIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 500));

        lblMovil.setBackground(new java.awt.Color(238, 112, 82));
        lblMovil.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lblMovil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblMovilMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMovilMouseMoved(evt);
            }
        });
        lblMovil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMovilMousePressed(evt);
            }
        });
        lblMovil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setBackground(new java.awt.Color(238, 112, 82));
        lblClose.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblClose.setForeground(new java.awt.Color(238, 112, 82));
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/Delete_32px.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCloseMouseMoved(evt);
            }
        });
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        lblMovil.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 5, -1, 20));

        lblMinimize.setBackground(new java.awt.Color(238, 112, 82));
        lblMinimize.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(238, 112, 82));
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/Expand Arrow_32px.png"))); // NOI18N
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseMoved(evt);
            }
        });
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });
        lblMovil.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 5, -1, 20));

        getContentPane().add(lblMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 570, 30));

        jpApplicactions.setBorder(null);

        jpMenu.setBackground(new java.awt.Color(255, 255, 255));
        jpMenu.setForeground(new java.awt.Color(255, 97, 71));
        jpMenu.setToolTipText("");
        jpMenu.setAutoscrolls(true);
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblApp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Google_Drive_96px.png"))); // NOI18N
        lblApp1.setToolTipText("");
        lblApp1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblApp1MouseMoved(evt);
            }
        });
        lblApp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApp1MouseExited(evt);
            }
        });
        jpMenu.add(lblApp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 130));

        lblApp6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApp6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Clock_96px.png"))); // NOI18N
        lblApp6.setToolTipText("");
        lblApp6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblApp6MouseMoved(evt);
            }
        });
        lblApp6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApp6MouseExited(evt);
            }
        });
        jpMenu.add(lblApp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 150, 140));

        lblApp5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApp5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Handshake_96px.png"))); // NOI18N
        lblApp5.setToolTipText("");
        lblApp5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblApp5MouseMoved(evt);
            }
        });
        lblApp5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApp5MouseExited(evt);
            }
        });
        jpMenu.add(lblApp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 140, 130));

        lblApp4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Idea_96px.png"))); // NOI18N
        lblApp4.setToolTipText("");
        lblApp4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblApp4MouseMoved(evt);
            }
        });
        lblApp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApp4MouseExited(evt);
            }
        });
        jpMenu.add(lblApp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, 140));

        lblApp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Maintenance_96px.png"))); // NOI18N
        lblApp2.setToolTipText("");
        lblApp2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblApp2MouseMoved(evt);
            }
        });
        lblApp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApp2MouseExited(evt);
            }
        });
        jpMenu.add(lblApp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 150, 130));

        lblApp3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Today_96px.png"))); // NOI18N
        lblApp3.setToolTipText("");
        lblApp3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblApp3MouseMoved(evt);
            }
        });
        lblApp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApp3MouseExited(evt);
            }
        });
        jpMenu.add(lblApp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 150, 140));

        jLabel13.setBackground(new java.awt.Color(238, 112, 82));
        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 99, 71));
        jLabel13.setText("Mediciones");
        jpMenu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        jLabel14.setBackground(new java.awt.Color(238, 112, 82));
        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 99, 71));
        jLabel14.setText("Documentos");
        jpMenu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel15.setBackground(new java.awt.Color(238, 112, 82));
        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 99, 71));
        jLabel15.setText("Herramientas");
        jpMenu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel16.setBackground(new java.awt.Color(238, 112, 82));
        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 99, 71));
        jLabel16.setText("Actividades");
        jpMenu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jLabel17.setBackground(new java.awt.Color(238, 112, 82));
        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 99, 71));
        jLabel17.setText("Innovación");
        jpMenu.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel18.setBackground(new java.awt.Color(238, 112, 82));
        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 99, 71));
        jLabel18.setText("Clientes");
        jpMenu.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        jpMenu.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 300, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Search_32px_2.png"))); // NOI18N
        jpMenu.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        lblApp7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApp7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Google_Drive_96px.png"))); // NOI18N
        lblApp7.setToolTipText("");
        lblApp7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblApp7MouseMoved(evt);
            }
        });
        lblApp7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApp7MouseExited(evt);
            }
        });
        jpMenu.add(lblApp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, 130));

        lblApp8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApp8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Clock_96px.png"))); // NOI18N
        lblApp8.setToolTipText("");
        lblApp8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblApp8MouseMoved(evt);
            }
        });
        lblApp8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApp8MouseExited(evt);
            }
        });
        jpMenu.add(lblApp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 150, 140));

        lblApp9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApp9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Handshake_96px.png"))); // NOI18N
        lblApp9.setToolTipText("");
        lblApp9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblApp9MouseMoved(evt);
            }
        });
        lblApp9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApp9MouseExited(evt);
            }
        });
        jpMenu.add(lblApp9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 140, 130));

        lblApp10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApp10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Idea_96px.png"))); // NOI18N
        lblApp10.setToolTipText("");
        lblApp10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblApp10MouseMoved(evt);
            }
        });
        lblApp10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApp10MouseExited(evt);
            }
        });
        jpMenu.add(lblApp10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 140, 140));

        lblApp11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApp11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Maintenance_96px.png"))); // NOI18N
        lblApp11.setToolTipText("");
        lblApp11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblApp11MouseMoved(evt);
            }
        });
        lblApp11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApp11MouseExited(evt);
            }
        });
        jpMenu.add(lblApp11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 150, 130));

        lblApp12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApp12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/siserp/resources/icons8_Today_96px.png"))); // NOI18N
        lblApp12.setToolTipText("");
        lblApp12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblApp12MouseMoved(evt);
            }
        });
        lblApp12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApp12MouseExited(evt);
            }
        });
        jpMenu.add(lblApp12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 150, 140));

        jLabel20.setBackground(new java.awt.Color(238, 112, 82));
        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 99, 71));
        jLabel20.setText("Mediciones");
        jpMenu.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 600, -1, -1));

        jLabel21.setBackground(new java.awt.Color(238, 112, 82));
        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 99, 71));
        jLabel21.setText("Documentos");
        jpMenu.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel22.setBackground(new java.awt.Color(238, 112, 82));
        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 99, 71));
        jLabel22.setText("Herramientas");
        jpMenu.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        jLabel23.setBackground(new java.awt.Color(238, 112, 82));
        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 99, 71));
        jLabel23.setText("Actividades");
        jpMenu.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        jLabel24.setBackground(new java.awt.Color(238, 112, 82));
        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 99, 71));
        jLabel24.setText("Innovación");
        jpMenu.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, -1, -1));

        jLabel25.setBackground(new java.awt.Color(238, 112, 82));
        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 99, 71));
        jLabel25.setText("Clientes");
        jpMenu.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, -1, -1));

        jpApplicactions.setViewportView(jpMenu);

        getContentPane().add(jpApplicactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 570, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        //AnimationClass animacion = new AnimationClass();
        /*if(blnAnimacion == false){
            animacion.jLabelYDown(-30, 10, 30, 5, lblInternet);
            animacion.jLabelYDown(-30, 10, 20, 5, lblCalculadora);
            animacion.jLabelYDown(-30, 10, 10, 5, lblMusica);
            blnAnimacion = true;
        }else{
            animacion.jLabelYUp(10, -30, 10, 5, lblInternet);
            animacion.jLabelYUp(10, -30, 20, 5, lblCalculadora);
            animacion.jLabelYUp(10, -30, 30, 5, lblMusica);
            blnAnimacion = false;
        }*/
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(frmLoginOrange.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblApp1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp1MouseMoved
        lblApp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_lblApp1MouseMoved

    private void lblApp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp1MouseExited
        lblApp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_lblApp1MouseExited

    private void lblApp2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp2MouseMoved
        lblApp2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_lblApp2MouseMoved

    private void lblApp2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp2MouseExited
        lblApp2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_lblApp2MouseExited

    private void lblApp3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp3MouseMoved
        lblApp3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_lblApp3MouseMoved

    private void lblApp3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp3MouseExited
        lblApp3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_lblApp3MouseExited

    private void lblApp4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp4MouseMoved
        lblApp4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_lblApp4MouseMoved

    private void lblApp4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp4MouseExited
        lblApp4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_lblApp4MouseExited

    private void lblApp5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp5MouseMoved
        lblApp5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_lblApp5MouseMoved

    private void lblApp5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp5MouseExited
        lblApp5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_lblApp5MouseExited

    private void lblApp6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp6MouseMoved
        lblApp6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_lblApp6MouseMoved

    private void lblApp6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp6MouseExited
        lblApp6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_lblApp6MouseExited

    private void lblInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInternetMouseClicked
        openInternet();
    }//GEN-LAST:event_lblInternetMouseClicked

    private void lblCalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalculadoraMouseClicked
        try{
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            p.waitFor();
        } catch(Exception e){
            JOptionPane.showConfirmDialog(this, e);
        }
    }//GEN-LAST:event_lblCalculadoraMouseClicked

    private void lblCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseMoved
        lblClose.setBackground(Color.BLACK);
        lblClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,99,71)));
    }//GEN-LAST:event_lblCloseMouseMoved

    private void lblMinimizeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseMoved
        lblMinimize.setBackground(Color.BLUE);
        lblMinimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,99,71)));
    }//GEN-LAST:event_lblMinimizeMouseMoved

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
       lblMinimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblApp7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApp7MouseMoved

    private void lblApp7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApp7MouseExited

    private void lblApp8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp8MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApp8MouseMoved

    private void lblApp8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApp8MouseExited

    private void lblApp9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp9MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApp9MouseMoved

    private void lblApp9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApp9MouseExited

    private void lblApp10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp10MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApp10MouseMoved

    private void lblApp10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApp10MouseExited

    private void lblApp11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp11MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApp11MouseMoved

    private void lblApp11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApp11MouseExited

    private void lblApp12MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp12MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApp12MouseMoved

    private void lblApp12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApp12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApp12MouseExited

    private void lblMovilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovilMousePressed
        // TODO add your handling code here:
        MovtoX =  evt.getX();
        MovtoY =  evt.getY();
    }//GEN-LAST:event_lblMovilMousePressed

    private void lblMovilMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovilMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMovilMouseMoved

    private void lblMovilMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovilMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - MovtoX, this.getLocation().y + evt.getY() - MovtoY);
    }//GEN-LAST:event_lblMovilMouseDragged

    private void lblRegistroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseMoved
         lblRegistro.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblRegistroMouseMoved

    private void lblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseClicked
        jintRegister reg = new jintRegister();
        reg.show();
    }//GEN-LAST:event_lblRegistroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLoginOrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLoginOrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLoginOrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLoginOrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLoginOrange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JScrollPane jpApplicactions;
    private javax.swing.JPanel jpIngreso;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JLabel lblApp1;
    private javax.swing.JLabel lblApp10;
    private javax.swing.JLabel lblApp11;
    private javax.swing.JLabel lblApp12;
    private javax.swing.JLabel lblApp2;
    private javax.swing.JLabel lblApp3;
    private javax.swing.JLabel lblApp4;
    private javax.swing.JLabel lblApp5;
    private javax.swing.JLabel lblApp6;
    private javax.swing.JLabel lblApp7;
    private javax.swing.JLabel lblApp8;
    private javax.swing.JLabel lblApp9;
    private javax.swing.JLabel lblCalculadora;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblInternet;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JPanel lblMovil;
    private javax.swing.JLabel lblMusica;
    private javax.swing.JLabel lblRegistro;
    // End of variables declaration//GEN-END:variables
}
